function gain_tuner_gui()
% GAIN_TUNER_GUI  Tune PID gains and restart the sim with one button press.
%
% Launches sim_multi.m (via run()) with gains injected before build_controllers
% is called. No MAT file polling needed.
close all 
clear all
    %% ── Default gains ────────────────────────────────────────────────────
    D = struct( ...
        'pos_N_Kp',   1.0,  'pos_E_Kp',   1.0,  'pos_D_Kp',   1.0,  ...
        'vel_N_Kp',   2.0,  'vel_N_Ki',   1.0,  'vel_N_Kd',   0.5,  ...
        'vel_E_Kp',   2.0,  'vel_E_Ki',   1.0,  'vel_E_Kd',   0.5,  ...
        'vel_D_Kp',   5.0,  'vel_D_Ki',   2.0,  'vel_D_Kd',   0.0,  ...
        'att_roll_Kp',  4.5, 'att_pitch_Kp', 4.5, 'att_yaw_Kp',  4.5, ...
        'rate_roll_Kp',  8.0, 'rate_roll_Ki',  0, 'rate_roll_Kd',  1.5, ...
        'rate_pitch_Kp', 8.0, 'rate_pitch_Ki', 0.135, 'rate_pitch_Kd', 1.5, ...
        'rate_yaw_Kp',   0.18,  'rate_yaw_Ki',   0.018, 'rate_yaw_Kd',   0.0,   ...
        'indi_roll_Kp',  0.35,  'indi_pitch_Kp', 0.35  ...
    );

    %% ── Figure ───────────────────────────────────────────────────────────
    fig = uifigure('Name','Gain Tuner', ...
                   'Position',[80 80 800 660], ...
                   'Color',[0.15 0.15 0.18]);

    uilabel(fig,'Text','Multicopter Gain Tuner', ...
        'Position',[0 630 800 28],'HorizontalAlignment','center', ...
        'FontSize',16,'FontWeight','bold', ...
        'FontColor',[0.9 0.9 0.9],'BackgroundColor',[0.15 0.15 0.18]);

    tg = uitabgroup(fig,'Position',[5 80 790 548]);
    %tg.BackgroundColor = [0.2 0.2 0.23];

    % Status bar
    status_lbl = uilabel(fig, ...
        'Text','Ready — adjust gains then press Update & Restart.', ...
        'Position',[10 48 780 26], ...
        'FontColor',[0.6 0.85 0.6],'FontSize',11, ...
        'BackgroundColor',[0.12 0.12 0.14]);

    % Buttons
    uibutton(fig,'Text','Reset to Defaults', ...
        'Position',[10 10 160 30], ...
        'BackgroundColor',[0.3 0.18 0.18],'FontColor','white', ...
        'ButtonPushedFcn',@(~,~) reset_all());

    uibutton(fig,'Text','Update & Restart Sim', ...
        'Position',[620 10 170 30], ...
        'BackgroundColor',[0.15 0.38 0.18],'FontColor','white', ...
        'FontWeight','bold', ...
        'ButtonPushedFcn',@(~,~) restart_sim());

    %% ── Tab definitions ──────────────────────────────────────────────────
    tab_specs = { ...
      'Position', { ...
        {'North Kp','pos_N_Kp', 0, 5,  D.pos_N_Kp}, ...
        {'East  Kp','pos_E_Kp', 0, 5,  D.pos_E_Kp}, ...
        {'Down  Kp','pos_D_Kp', 0, 5,  D.pos_D_Kp}  ...
      }; ...
      'Velocity', { ...
        {'North Kp','vel_N_Kp', 0, 10, D.vel_N_Kp}, ...
        {'North Ki','vel_N_Ki', 0, 5,  D.vel_N_Ki}, ...
        {'North Kd','vel_N_Kd', 0, 3,  D.vel_N_Kd}, ...
        {'East  Kp','vel_E_Kp', 0, 10, D.vel_E_Kp}, ...
        {'East  Ki','vel_E_Ki', 0, 5,  D.vel_E_Ki}, ...
        {'East  Kd','vel_E_Kd', 0, 3,  D.vel_E_Kd}, ...
        {'Down  Kp','vel_D_Kp', 0, 15, D.vel_D_Kp}, ...
        {'Down  Ki','vel_D_Ki', 0, 8,  D.vel_D_Ki}, ...
        {'Down  Kd','vel_D_Kd', 0, 3,  D.vel_D_Kd}  ...
      }; ...
      'Attitude', { ...
        {'Roll  Kp','att_roll_Kp',  0, 15, D.att_roll_Kp},  ...
        {'Pitch Kp','att_pitch_Kp', 0, 15, D.att_pitch_Kp}, ...
        {'Yaw   Kp','att_yaw_Kp',   0, 15, D.att_yaw_Kp}   ...
      }; ...
      'Rates', { ...
        {'Roll  Kp','rate_roll_Kp',  0, 15,    D.rate_roll_Kp},  ...
        {'Roll  Ki','rate_roll_Ki',  0, 15,    D.rate_roll_Ki},  ...
        {'Roll  Kd','rate_roll_Kd',  0, 15, D.rate_roll_Kd}, ...
        {'Pitch Kp','rate_pitch_Kp', 0, 15,    D.rate_pitch_Kp}, ...
        {'Pitch Ki','rate_pitch_Ki', 0, 15,    D.rate_pitch_Ki}, ...
        {'Pitch Kd','rate_pitch_Kd', 0, 15, D.rate_pitch_Kd},...
        {'Yaw   Kp','rate_yaw_Kp',  0, 1,    D.rate_yaw_Kp},  ...
        {'Yaw   Ki','rate_yaw_Ki',  0, 0.2,  D.rate_yaw_Ki},  ...
        {'Yaw   Kd','rate_yaw_Kd',  0, 0.02, D.rate_yaw_Kd}   ...
      }; ...
      'INDI', { ...
        {'Roll  Kp','indi_roll_Kp',  0, 500, D.indi_roll_Kp}, ...
        {'Pitch Kp','indi_pitch_Kp', 0, 500, D.indi_pitch_Kp}  ...
      } ...
    };

    sliders   = struct();
    editboxes = struct();

    for ti = 1:size(tab_specs,1)
        t = uitab(tg,'Title',tab_specs{ti,1}, ...
                  'BackgroundColor',[0.2 0.2 0.23]);
        build_tab(t, tab_specs{ti,2});
    end

    %% ── Tab builder ──────────────────────────────────────────────────────
    function build_tab(tab, rows)
        ROW_H = 46;
        TOP   = numel(rows)*ROW_H + 30;

        scroll = uipanel(tab,'BorderType','none', ...
            'BackgroundColor',[0.2 0.2 0.23], ...
            'Position',[0 0 782 540],'Scrollable','on');

        % Column headers
        hdrs = {'Gain','Value','Min','Slider','Max'};
        hx   = [10 120 200 270 685];
        for c = 1:numel(hdrs)
            uilabel(scroll,'Text',hdrs{c}, ...
                'Position',[hx(c) TOP+4 80 20], ...
                'FontColor',[0.55 0.75 0.95],'FontWeight','bold', ...
                'BackgroundColor',[0.2 0.2 0.23]);
        end

        for ri = 1:numel(rows)
            row   = rows{ri};
            lname = row{1}; fname = row{2};
            lo    = row{3}; hi    = row{4}; val = row{5};
            y = TOP - ri*ROW_H + 8;

            uilabel(scroll,'Text',lname, ...
                'Position',[10 y 108 26], ...
                'FontColor',[0.85 0.85 0.85], ...
                'BackgroundColor',[0.2 0.2 0.23],'FontSize',12);

            ef = uieditfield(scroll,'numeric','Value',val, ...
                'Limits',[lo hi], ...
                'Position',[120 y 72 26],'FontSize',11, ...
                'BackgroundColor',[0.13 0.13 0.16],'FontColor','white', ...
                'ValueChangedFcn',@(src,~) on_edit(fname,src));
            editboxes.(fname) = ef;

            uilabel(scroll,'Text',sprintf('%.4g',lo), ...
                'Position',[200 y 60 26], ...
                'FontColor',[0.5 0.5 0.5], ...
                'BackgroundColor',[0.2 0.2 0.23],'FontSize',10);

            sl = uislider(scroll,'Limits',[lo hi],'Value',val, ...
                'Position',[270 y+14 408 3], ...
                'MajorTicks',[],'MinorTicks',[], ...
                'ValueChangedFcn',@(src,~) on_slider(fname,src));
            sliders.(fname) = sl;

            uilabel(scroll,'Text',sprintf('%.4g',hi), ...
                'Position',[683 y 60 26], ...
                'FontColor',[0.5 0.5 0.5], ...
                'BackgroundColor',[0.2 0.2 0.23],'FontSize',10);
        end
    end

    %% ── Slider / edit callbacks ──────────────────────────────────────────
    function on_slider(fname, src)
        v = round(src.Value, 4, 'significant');
        editboxes.(fname).Value = v;
    end

    function on_edit(fname, src)
        sliders.(fname).Value = src.Value;
    end

    function reset_all()
        fnames = fieldnames(D);
        for k = 1:numel(fnames)
            fn = fnames{k};
            if isfield(sliders, fn)
                sliders.(fn).Value   = D.(fn);
                editboxes.(fn).Value = D.(fn);
            end
        end
        status_lbl.Text = 'Reset to defaults — press Update & Restart to apply.';
    end

    %% ── Collect current gains from GUI ───────────────────────────────────
    function g = collect_gains()
        g = struct();
        fnames = fieldnames(sliders);
        for k = 1:numel(fnames)
            fn = fnames{k};
            g.(fn) = sliders.(fn).Value;
        end
    end

    %% ── Kill sim, clear workspace, relaunch ──────────────────────────────
  function restart_sim()
    status_lbl.Text = 'Clearing state...';
    drawnow;

    gains = collect_gains();
    evalin('base','clearvars');
    clear functions  %#ok<CLFUNC>
    assignin('base','TUNER_GAINS', gains);

    status_lbl.Text = 'Running sim...';
    drawnow;

    gui_dir  = fileparts(mfilename('fullpath'));
    sim_path = fullfile(gui_dir, 'SIM_multicopter_INDI_tuning.m');

    if ~isfile(sim_path)
        status_lbl.Text = sprintf('ERROR: cannot find %s', sim_path);
        return
    end

    evalin('base', sprintf("run('%s')", sim_path));

    % Retrieve history logged into base workspace by the sim
    if ~evalin('base','exist(''history'',''var'')')
        status_lbl.Text = 'Sim finished but no history returned.';
        return
    end

    history = evalin('base','history');
    plot_history(history);
    status_lbl.Text = sprintf('Done. Sim time: %.1f s', history.t(end));
end

    function plot_history(h)
    fh = findobj('Type','figure','Name','Sim Results');
    if isempty(fh)
        fh = figure('Name','Sim Results','NumberTitle','off', ...
                    'Position',[880 20 980 1100], ...
                    'Color',[0.13 0.13 0.15]);
    else
        clf(fh);
    end

    BG  = [0.13 0.13 0.15];
    AXC = [0.20 0.20 0.23];
    TC  = [0.90 0.90 0.90];
    cols     = {[0.35 0.75 0.95], [0.45 0.90 0.55], [0.95 0.60 0.35]};
    cols_tgt = {[0.20 0.48 0.65], [0.25 0.58 0.32], [0.68 0.38 0.18]};

    % Each row: {title, actual data, target data or [], actual labels, target labels}
    panels = { ...
        'Position (m)', ...
            h.pos,      h.tgt_pos, ...
            {'N','E','D'}, {'N tgt','E tgt','D tgt'}; ...
        'Velocity (m/s)', ...
            h.vel,      h.tgt_vel, ...
            {'vN','vE','vD'}, {'vN tgt','vE tgt','vD tgt'}; ...
        'Acceleration body (m/s²)', ...
            h.acc,      [], ...
            {'aN','aE','aD'}, {}; ...
        'Attitude (deg)', ...
            h.att,      h.tgt_att, ...
            {'Roll','Pitch','Yaw'}, {'\phi tgt','\theta tgt','\psi tgt'}; ...
        'Gyro / Rate cmd (deg/s)', ...
            h.gyr,      h.tgt_rate, ...
            {'p','q','r'}, {'p cmd','q cmd','r cmd'}; ...
        'Rot Accel / Accel cmd (deg/s²)', ...
            h.rot_acc,  h.tgt_accel, ...
            {'\alpha_p','\alpha_q','\alpha_r'}, {'\alphap cmd','\alphaq cmd','\alphar cmd'}; ...
        'Controller torques \tau (N·m)', ...
            h.tau,      [], ...
            {'\tau_{roll}','\tau_{pitch}','\tau_{yaw}'}, {}; ...
    };

    n = size(panels,1);
    mg = struct('l',0.09,'r',0.21,'t',0.03,'b',0.05,'gap',0.010);
    ax_h = (1 - mg.t - mg.b - (n-1)*mg.gap) / n;

    axes_h = gobjects(n,1);
    for p = 1:n
        bot = mg.b + (n-p)*(ax_h + mg.gap);
        ax  = axes('Parent',fh, ...
                   'Position',[mg.l, bot, 1-mg.l-mg.r, ax_h]);
        axes_h(p) = ax;

        set(ax,'Color',AXC,'XColor',TC,'YColor',TC,'FontSize',8, ...
               'GridColor',[0.4 0.4 0.4],'GridAlpha',0.35,'TickDir','out');
        grid(ax,'on'); hold(ax,'on'); box(ax,'off');

        actual = panels{p,2};
        target = panels{p,3};
        al     = panels{p,4};
        tl     = panels{p,5};

        % Actual — solid
        for ch = 1:3
            plot(ax, h.t, actual(ch,:), '-', ...
                 'Color', cols{ch}, 'LineWidth', 1.4, ...
                 'DisplayName', al{ch});
        end

        % Target — dashed, darker shade of same colour
        if ~isempty(target)
            for ch = 1:3
                plot(ax, h.t, target(ch,:), '--', ...
                     'Color', cols_tgt{ch}, 'LineWidth', 1.0, ...
                     'DisplayName', tl{ch});
            end
        end

        title(ax, panels{p,1}, 'Color',TC,'FontSize',9,'FontWeight','bold');

        leg = legend(ax,'show','Location','eastoutside','FontSize',7);
        leg.TextColor = TC;
        leg.Color     = AXC;
        leg.EdgeColor = [0.35 0.35 0.38];

        if p < n
            set(ax,'XTickLabel',[]);
        else
            xlabel(ax,'Time (s)','Color',TC,'FontSize',9);
        end
    end

    linkaxes(axes_h,'x');
    sgtitle(fh,'Simulation Results','Color',TC,'FontSize',12,'FontWeight','bold');
    set(fh,'Color',BG);
end
end

