clc
clearvars
close all
addpath(genpath('../../MATLAB'))

% Physics of a multi copter

% load in the parameters for a frame, generated by Copter.m
try
    state = load('rtos_drone','copter');
catch
     run('rtos_drone.m')
    fprintf('Could not find rtos_drone.mat file, running copter.m\n')
    return
end


% Setup environmental conditions
state.environment.density = 1.225; % (kg/m^3)
state.gravity_mss = 9.80665; % (m/s^2)

% Setup the time step size for the Physics model
max_timestep = 1/400;

% define init and time setup functions
init_function = @init;
physics_function = @physics_step;

% setup connection
SITL_connector(state,init_function,physics_function,max_timestep);

% Simulator model must take and return a structure with the felids: 
% gyro(roll, pitch, yaw) (radians/sec) body frame
% attitude(roll, pitch yaw) (radians)
% accel(north, east, down) (m/s^2) body frame
% velocity(north, east,down) (m/s) earth frame
% position(north, east, down) (m) earth frame 
% the structure can have any other felids required for the physics model

% init values
function state = init(state)

for i = 1:numel(state.copter.motors)
    state.copter.motors(i).thrust = zeros(1,state.copter.motor_model.nz); % 
    state.copter.motors(i).torque = 0;
    state.copter.motors(i).pwm = zeros(1,state.copter.motor_model.np); % pwm inputs from time t-4 to t-1 inclusive
end
state.gyro = [0;0;0]; % (rad/sec)
state.dcm = diag([1,1,1]); % direction cosine matrix
state.attitude = [0;0;0]; % (radians) (roll, pitch, yaw)
state.accel = [0;0;0]; % (m/s^2) body frame
state.rot_accel = [0;0;0]; % (m/s^2) body frame
state.velocity = [0;0;0]; % (m/s) earth frame
state.position = [0;0;0]; % (m) earth frame
state.bf_velo = [0;0;0]; % (m/s) body frame
end

% compute thrust from PWM
function [thrust_new,torque_new] = fit_pwm_to_thrust_torque(state,pwm_in,i)
% poly4 fit from sysid mean_fit       
%mean_fit = 1546;
%std_fit = 255.6;
%pwm_in = (pwm_in - state.copter.motor_model.pwm_mean)/state.copter.motor_model.pwm_std;

state.copter.motors(i).pwm = [pwm_in,state.copter.motors(i).pwm(1:end-1)];

% get steady state thrust first 

thrust_new = state.copter.motor_model.coeff_zeros*state.copter.motors(i).pwm'...
                -state.copter.motor_model.coeff_poles*state.copter.motors(i).thrust';

torque_new = [];

state.copter.motors(i).thrust = [thrust_new,state.copter.motors(i).thrust(1:end-1)];
state.copter.motors(i).torque = [torque_new,state.copter.motors(i).torque(1:end-1)];



end

% compute torque from PWM

% Take a physics time step
function state = physics_step(pwm_in,state)

% Calculate the torque and thrust, assume RPM is last step value
for i = 1:numel(state.copter.motors)
    motor = state.copter.motors(i);

    % Calculate the thrust and torque
    [thrust_pwm,torque_pwm] = fit_pwm_to_thrust_torque(pwm_in(motor.channel));
    
   
    %thrust = thrust_pwm;
    %torque = torque_pwm;

    % calculate resulting moments
    moment_roll = thrust * motor.location(1);
    moment_pitch = thrust * motor.location(2);
    moment_yaw = -torque * motor.direction;
    
    % sprintf("Motor i:%d Thrust: %0.4f",i,thrust)
    
    % Update main structure
    state.copter.motors(i).torque = torque;
    state.copter.motors(i).thrust = thrust;
    state.copter.motors(i).torque_pwm_prev = torque_pwm;
    state.copter.motors(i).thrust_pwm_prev = thrust_pwm;
    state.copter.motors(i).moment_roll = moment_roll;
    state.copter.motors(i).moment_pitch = moment_pitch;
    state.copter.motors(i).moment_yaw = moment_yaw;
end

drag = sign(state.bf_velo) .* state.copter.cd .* state.copter.cd_ref_area .* 0.5 .* state.environment.density .* state.bf_velo.^2;

% Calculate the forces about the CG (N,E,D) (body frame)
force = [0;0;-sum([state.copter.motors.thrust])] - drag;

% estimate rotational drag
rotational_drag = 0.2 * sign(state.gyro) .* state.gyro.^2; % estimated to give a reasonable max rotation rate
% Update attitude, moments to rotational acceleration to rotational velocity to attitude
moments = [-sum([state.copter.motors.moment_roll]);sum([state.copter.motors.moment_pitch]);sum([state.copter.motors.moment_yaw])] - rotational_drag;
%sprintf(" Pitch Torque: %0.4f, \n",moments(2))

state = update_dynamics(state,force,moments);

%publish_animation(state);
end

function publish_animation(state)
% publish to web
% MATLAB script to publish Quadcopter state

% Fill array
    data_to_send = single([state.position(1:2)',-state.position(3), state.attitude',0.0167*state.rot_accel']);

    % 2. Write raw binary (Extremely fast)
    write(state.u, data_to_send, "single", state.target_ip, state.target_port);

end
% integrate the acceleration resulting from the forces and moments to get the
% new state

function state = update_dynamics(state,force,moments)

rot_accel = (moments' / state.copter.inertia)';
state.rot_accel = rot_accel;

state.gyro = state.gyro + rot_accel * state.delta_t;

% Constrain to 2000 deg per second, this is what typical sensors max out at
state.gyro = max(state.gyro,deg2rad(-2000));
state.gyro = min(state.gyro,deg2rad(2000));

% update the dcm and attitude
[state.dcm, state.attitude] = rotate_dcm(state.dcm,state.gyro * state.delta_t);

% body frame accelerations
state.accel = force / state.copter.mass;

% earth frame accelerations (NED)
accel_ef = state.dcm * state.accel;
accel_ef(3) = accel_ef(3) + state.gravity_mss;

% if we're on the ground, then our vertical acceleration is limited
% to zero. This effectively adds the force of the ground on the aircraft
if state.position(3) >= 0 && accel_ef(3) > 0
    accel_ef(3) = 0;
end

% work out acceleration as seen by the accelerometers. It sees the kinematic
% acceleration (ie. real movement), plus gravity
state.accel = state.dcm' * (accel_ef + [0; 0; -state.gravity_mss]);

state.velocity = state.velocity + accel_ef * state.delta_t;
state.position = state.position + state.velocity * state.delta_t;

% make sure we can't go underground (NED so underground is positive)
if state.position(3) >= 0
    state.position(3) = 0;
    state.velocity = [0;0;0];
    state.gyro = [0;0;0];
end

% calculate the body frame velocity for drag calculation
state.bf_velo = state.dcm' * state.velocity;



end

function [dcm, euler] = rotate_dcm(dcm, ang)

% rotate
delta = [dcm(1,2) * ang(3) - dcm(1,3) * ang(2),         dcm(1,3) * ang(1) - dcm(1,1) * ang(3),      dcm(1,1) * ang(2) - dcm(1,2) * ang(1);
         dcm(2,2) * ang(3) - dcm(2,3) * ang(2),         dcm(2,3) * ang(1) - dcm(2,1) * ang(3),      dcm(2,1) * ang(2) - dcm(2,2) * ang(1);
         dcm(3,2) * ang(3) - dcm(3,3) * ang(2),         dcm(3,3) * ang(1) - dcm(3,1) * ang(3),      dcm(3,1) * ang(2) - dcm(3,2) * ang(1)];

dcm = dcm + delta;

% normalise
a = dcm(1,:);
b = dcm(2,:);
error = a * b';
t0 = a - (b *(0.5 * error));
t1 = b - (a *(0.5 * error));
t2 = cross(t0,t1);
dcm(1,:) = t0 * (1/norm(t0));
dcm(2,:) = t1 * (1/norm(t1));
dcm(3,:) = t2 * (1/norm(t2));

% calculate euler angles
euler = [atan2(dcm(3,2),dcm(3,3)); -asin(dcm(3,1)); atan2(dcm(2,1),dcm(1,1))]; 

end

